package net.hydra.jojomod.registry;

import net.hydra.jojomod.Roundabout;
import net.hydra.jojomod.block.*;
import net.hydra.jojomod.client.ModStrayModels;
import net.hydra.jojomod.client.models.RoadRollerStrayModel;
import net.hydra.jojomod.client.models.WornBloodyStoneMaskModel;
import net.hydra.jojomod.client.models.WornStoneMaskModel;
import net.hydra.jojomod.client.models.corpses.renderers.*;
import net.hydra.jojomod.client.models.paintings.MonaLisaPaintingRenderer;
import net.hydra.jojomod.client.models.paintings.VanGoghPaintingRenderer;
import net.hydra.jojomod.client.models.paintings.VenusPaintingRenderer;
import net.hydra.jojomod.client.models.projectile.*;
import net.hydra.jojomod.client.models.projectile.renderers.*;
import net.hydra.jojomod.client.models.stand.*;
import net.hydra.jojomod.client.models.stand.renderers.*;
import net.hydra.jojomod.client.models.visages.*;
import net.hydra.jojomod.client.models.visages.parts.*;
import net.hydra.jojomod.client.models.visages.renderers.*;
import net.hydra.jojomod.client.models.worn_stand.*;
import net.hydra.jojomod.client.models.substand.renderers.D4CCloneRenderer;
import net.hydra.jojomod.client.models.substand.renderers.FogCloneRenderer;
import net.hydra.jojomod.client.models.mobs.TerrierEntityModel;
import net.hydra.jojomod.client.models.mobs.renderers.TerrierEntityRenderer;
import net.hydra.jojomod.client.models.layers.MagiciansRedSpinEffectLayer;
import net.hydra.jojomod.client.models.layers.ModEntityRendererClient;
import net.hydra.jojomod.client.models.npcs.ZombieAestheticianModel;
import net.hydra.jojomod.client.models.npcs.renderers.ZombieAestheticianRenderer;
import net.hydra.jojomod.client.models.projectile.renderers.NoRenderer;
import net.hydra.jojomod.client.models.substand.renderers.EncasementBubbleRenderer;
import net.hydra.jojomod.client.models.substand.LifeTrackerModel;
import net.hydra.jojomod.client.models.substand.renderers.LifeTrackerRenderer;
import net.hydra.jojomod.particles.*;
import net.hydra.jojomod.util.MainUtil;
import net.minecraft.client.particle.ExplodeParticle;
import net.minecraft.client.renderer.entity.ThrownItemRenderer;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.client.event.RegisterParticleProvidersEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;

@Mod.EventBusSubscriber(modid = Roundabout.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class ClientForgeEvents {

    @SubscribeEvent
    public static void onClientSetup(FMLClientSetupEvent event) {
        // This runs on client during mod loading (after registries)
        MainUtil.setClient();
    }
    @SubscribeEvent
    public static void registerRenderers(EntityRenderersEvent.RegisterRenderers event) {
        event.registerEntityRenderer(ForgeEntities.TERRIER_DOG.get(), TerrierEntityRenderer::new);
        event.registerEntityRenderer(ForgeEntities.STAR_PLATINUM.get(), StarPlatinumRenderer::new);
        event.registerEntityRenderer(ForgeEntities.STAR_PLATINUM_BASEBALL.get(), StarPlatinumBaseballRenderer::new);
        event.registerEntityRenderer(ForgeEntities.THE_WORLD.get(), TheWorldRenderer::new);
        event.registerEntityRenderer(ForgeEntities.THE_WORLD_ULTIMATE.get(), TheWorldUltimateRenderer::new);
        event.registerEntityRenderer(ForgeEntities.JUSTICE.get(), JusticeRenderer::new);
        event.registerEntityRenderer(ForgeEntities.MAGICIANS_RED.get(), MagiciansRedRenderer::new);
        event.registerEntityRenderer(ForgeEntities.MAGICIANS_RED_OVA.get(), MagiciansRedOVARenderer::new);
        event.registerEntityRenderer(ForgeEntities.SURVIVOR.get(), SurvivorRenderer::new);
        event.registerEntityRenderer(ForgeEntities.KILLER_QUEEN.get(), KillerQueenRenderer::new);
        event.registerEntityRenderer(ForgeEntities.D4C.get(), D4CRenderer::new);
        event.registerEntityRenderer(ForgeEntities.GREEN_DAY.get(), GreenDayRenderer::new);
        event.registerEntityRenderer(ForgeEntities.RATT.get(), RattRenderer::new);
        event.registerEntityRenderer(ForgeEntities.REDD.get(), ReddRenderer::new);
        event.registerEntityRenderer(ForgeEntities.CHAIR_RAT.get(), ChairRattRenderer::new);
        event.registerEntityRenderer(ForgeEntities.SOFT_AND_WET.get(), SoftAndWetRenderer::new);
        event.registerEntityRenderer(ForgeEntities.SOFT_AND_WET_DROWNED.get(), SoftAndWetDrownedRenderer::new);
        event.registerEntityRenderer(ForgeEntities.SOFT_AND_WET_DEBUT.get(), SoftAndWetDebutRenderer::new);
        event.registerEntityRenderer(ForgeEntities.SOFT_AND_WET_KILLER_QUEEN.get(), SoftAndWetKillerQueenRenderer::new);
        event.registerEntityRenderer(ForgeEntities.SOFT_AND_WET_KING.get(), SoftAndWetKingRenderer::new);
        event.registerEntityRenderer(ForgeEntities.KILLER_QUEEN.get(), KillerQueenRenderer::new);
        event.registerEntityRenderer(ForgeEntities.CINDERELLA.get(), CinderellaRenderer::new);
        event.registerEntityRenderer(ForgeEntities.WALKING_HEART.get(), WalkingHeartRenderer::new);
        event.registerEntityRenderer(ForgeEntities.JUSTICE_PIRATE.get(), JusticePirateRenderer::new);
        event.registerEntityRenderer(ForgeEntities.DARK_MIRAGE.get(), DarkMirageRenderer::new);
        event.registerEntityRenderer(ForgeEntities.DIVER_DOWN.get(), DiverDownRenderer::new);
        event.registerEntityRenderer(ForgeEntities.THROWN_HARPOON.get(), HarpoonRenderer::new);
        event.registerEntityRenderer(ForgeEntities.BLADED_BOWLER_HAT.get(), BladedBowlerHatRenderer::new);
        event.registerEntityRenderer(ForgeEntities.ROUNDABOUT_BULLET_ENTITY.get(), RoundaboutBulletEntityRenderer::new);
        event.registerEntityRenderer(ForgeEntities.THROWN_KNIFE.get(), KnifeRenderer::new);
        event.registerEntityRenderer(ForgeEntities.RATT_DART.get(), RattDartRenderer::new);
        event.registerEntityRenderer(ForgeEntities.THROWN_MATCH.get(), ThrownItemRenderer::new);
        event.registerEntityRenderer(ForgeEntities.THROWN_WATER_BOTTLE.get(), ThrownItemRenderer::new);
        event.registerEntityRenderer(ForgeEntities.GASOLINE_SPLATTER.get(), ThrownItemRenderer::new);
        event.registerEntityRenderer(ForgeEntities.FLESH_PILE.get(), ThrownItemRenderer::new);
        event.registerEntityRenderer(ForgeEntities.STAND_ARROW.get(), StandArrowRenderer::new);
        event.registerEntityRenderer(ForgeEntities.CROSSFIRE_HURRICANE.get(), CrossfireHurricaneRenderer::new);
        event.registerEntityRenderer(ForgeEntities.LIFE_TRACKER.get(), LifeTrackerRenderer::new);
        event.registerEntityRenderer(ForgeEntities.STAND_FIREBALL.get(), StandFireballRenderer::new);
        event.registerEntityRenderer(ForgeEntities.GASOLINE_CAN.get(), GasolineCanRenderer::new);
        event.registerEntityRenderer(ForgeEntities.THROWN_OBJECT.get(), ThrownObjectRenderer::new);
        event.registerEntityRenderer(ForgeEntities.CONCEALED_FLAME_OBJECT.get(), ConcealedFlameObjectRenderer::new);
        event.registerEntityRenderer(ForgeEntities.CINDERELLA_VISAGE_DISPLAY.get(), CinderellaVisageDisplayRenderer::new);
        event.registerEntityRenderer(ForgeEntities.GROUND_HURRICANE.get(), NoRenderer::new);
        event.registerEntityRenderer(ForgeEntities.GROUND_BUBBLE.get(), NoRenderer::new);
        event.registerEntityRenderer(ForgeEntities.PLUNDER_BUBBLE.get(), SoftAndWetBubbleRenderer::new);
        event.registerEntityRenderer(ForgeEntities.EXPLOSIVE_BUBBLE.get(), SoftAndWetBubbleRenderer::new);
        event.registerEntityRenderer(ForgeEntities.ITEM_LAUNCHING_BUBBLE_ENTITY.get(), SoftAndWetBubbleRenderer::new);
        event.registerEntityRenderer(ForgeEntities.GO_BEYOND.get(), NoRenderer::new);
        event.registerEntityRenderer(ForgeEntities.ENCASEMENT_BUBBLE.get(), EncasementBubbleRenderer::new);
        event.registerEntityRenderer(ForgeEntities.ROAD_ROLLER_ENTITY.get(), RoadRollerEntityRenderer::new);
        event.registerEntityRenderer(ForgeEntities.OVA_ENYA.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.ENYA.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.JOTARO.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.AVDOL.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.DIO.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.PARALLEL_DIEGO.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.JOSUKE_PART_EIGHT.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.AYA.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.AESTHETICIAN.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.ZOMBIE_AESTHETICIAN.get(), ZombieAestheticianRenderer::new);
        event.registerEntityRenderer(ForgeEntities.VALENTINE.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.RINGO.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.HATO.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.POCOLOCO.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.GUCCIO.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.SHIZUKA.get(), VisageBasisRenderer::new);
        event.registerEntityRenderer(ForgeEntities.STEVE_NPC.get(), PlayerNPCRenderer::new);
        event.registerEntityRenderer(ForgeEntities.ALEX_NPC.get(), PlayerAlexRenderer::new);
        event.registerEntityRenderer(ForgeEntities.FOG_CLONE.get(), FogCloneRenderer::new);
        event.registerEntityRenderer(ForgeEntities.D4C_CLONE.get(), D4CCloneRenderer::new);
        event.registerEntityRenderer(ForgeEntities.MODIFIED_NPC.get(), PlayerModifiedRenderer::new);
        event.registerEntityRenderer(ForgeEntities.FALLEN_ZOMBIE.get(), FallenZombieRenderer::new);
        event.registerEntityRenderer(ForgeEntities.FALLEN_SKELETON.get(), FallenSkeletonRenderer::new);
        event.registerEntityRenderer(ForgeEntities.FALLEN_SPIDER.get(), FallenSpiderRenderer::new);
        event.registerEntityRenderer(ForgeEntities.FALLEN_VILLAGER.get(), FallenVillagerRenderer::new);
        event.registerEntityRenderer(ForgeEntities.FALLEN_CREEPER.get(), FallenCreeperRenderer::new);
        event.registerEntityRenderer(ForgeEntities.FALLEN_PHANTOM.get(), FallenPhantomRenderer::new);
        event.registerEntityRenderer(ForgeEntities.VAN_GOUGH_PAINTING.get(), VanGoghPaintingRenderer::new);
        event.registerEntityRenderer(ForgeEntities.MONA_LISA_PAINTING.get(), MonaLisaPaintingRenderer::new);
        event.registerEntityRenderer(ForgeEntities.BIRTH_OF_VENUS_PAINTING.get(), VenusPaintingRenderer::new);

        event.registerBlockEntityRenderer(ForgeBlocks.STAND_FIRE_BLOCK_ENTITY.get(), StandFireRenderer::new);
        event.registerBlockEntityRenderer(ForgeBlocks.MIRROR_BLOCK_ENTITY.get(), MirrorBlockEntityRenderer::new);
        event.registerBlockEntityRenderer(ForgeBlocks.BUBBLE_SCAFFOLD_BLOCK_ENTITY.get(), BubbleScaffoldBlockEntityRenderer::new);
        event.registerBlockEntityRenderer(ForgeBlocks.INVISIBLE_BLOCK_ENTITY.get(), InvisiBlockEntityRenderer::new);
        event.registerBlockEntityRenderer(ForgeBlocks.D4C_LIGHT_BLOCK_ENTITY.get(), D4CLightBlockEntityRenderer::new);
    }

    @SubscribeEvent
    public static void registerLayerDefinitions(EntityRenderersEvent.RegisterLayerDefinitions event) {
        event.registerLayerDefinition(ModEntityRendererClient.WOLF_LAYER, TerrierEntityModel::createBodyLayerTerrier);
        event.registerLayerDefinition(ModEntityRendererClient.THE_WORLD_LAYER, TheWorldModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.THE_WORLD_ULTIMATE_LAYER, TheWorldUltimateModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.STAR_PLATINUM_LAYER, StarPlatinumModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.SURVIVOR_LAYER, SurvivorModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.STAR_PLATINUM_BASEBALL_LAYER, StarPlatinumBaseballModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.JUSTICE_LAYER, JusticeModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.MAGICIANS_RED_LAYER, MagiciansRedModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.MAGICIANS_RED_OVA_LAYER, MagiciansRedOVAModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.JUSTICE_PIRATE_LAYER, JusticePirateModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.D4C_LAYER, D4CModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.WALKING_HEART_LAYER, WalkingHeartModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.SOFT_AND_WET_LAYER, SoftAndWetModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.SOFT_AND_WET_DROWNED_LAYER, SoftAndWetDrownedModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.SOFT_AND_WET_DEBUT_LAYER, SoftAndWetDebutModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.SOFT_AND_WET_KING_LAYER, SoftAndWetKingModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.KILLER_QUEEN_LAYER, KillerQueenModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.SOFT_AND_WET_KILLER_QUEEN_LAYER, SoftAndWetKillerQueenModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.CINDERELLA_LAYER, CinderellaModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.DARK_MIRAGE_LAYER, DarkMirageModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.DIVER_DOWN_LAYER, DiverDownModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.KNIFE_LAYER, KnifeModel::createBodyLayer);
        event.registerLayerDefinition(ModEntityRendererClient.RATT_DART_LAYER, RattDartModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.HARPOON_LAYER, HarpoonModel::createBodyLayer);
        event.registerLayerDefinition(ModEntityRendererClient.BLADED_BOWLER_HAT_LAYER, BladedBowlerHatModel::createBodyLayer);
        event.registerLayerDefinition(ModEntityRendererClient.ROUNDABOUT_BULLET_LAYER, RoundaboutBulletModel::createBodyLayer);
        event.registerLayerDefinition(ModEntityRendererClient.CROSSFIRE_LAYER, CrossfireHurricaneModel::createBodyLayer);
        event.registerLayerDefinition(ModEntityRendererClient.CROSSFIRE_FIRESTORM_LAYER, CrossfireFirestormModel::createBodyLayer);
        event.registerLayerDefinition(ModEntityRendererClient.LIFE_DETECTOR, LifeTrackerModel::createBodyLayer);
        event.registerLayerDefinition(ModEntityRendererClient.STAND_FIREBALL_LAYER, StandFireballModel::createBodyLayer);
        event.registerLayerDefinition(ModEntityRendererClient.GASOLINE_LAYER, GasolineCanModel::createBodyLayer);
        event.registerLayerDefinition(ModEntityRendererClient.ZOMBIE_AESTHETICIAN_LAYER, ZombieAestheticianModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.STEVE_LAYER, PlayerSteveModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.ALEX_LAYER, PlayerAlexModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.MODIFIED_LAYER, PlayerModifiedModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.STAND_FIRE_LAYER, StandFireRenderer::createBodyLayer);
        event.registerLayerDefinition(ModEntityRendererClient.MR_SPIN_LAYER, MagiciansRedSpinEffectLayer::createLayer);
        event.registerLayerDefinition(ModEntityRendererClient.GREEN_DAY_LAYER, GreenDayModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.ROAD_ROLLER_LAYER, RoadRollerModel::createBodyLayer);
        event.registerLayerDefinition(ModEntityRendererClient.RATT_LAYER, RattModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.REDD_LAYER, ReddModel::getTexturedModelData);
        event.registerLayerDefinition(ModEntityRendererClient.CHAIR_RATT_LAYER, ChairRattModel::getTexturedModelData);
        ModStrayModels.SHOOTING_ARM = new SoftAndWetShootingArmModel();
        ModStrayModels.HEY_YA = new HeyYaModel();
        ModStrayModels.BOWLER_HAT = new BowlerHatModel();
        ModStrayModels.WORN_STONE_MASK = new WornStoneMaskModel();
        ModStrayModels.WORN_BLOODY_STONE_MASK = new WornBloodyStoneMaskModel();
        ModStrayModels.RATT_SHOULDER = new RattShoulderModel();
        ModStrayModels.REDD_SHOULDER = new ReddShoulderModel();
        ModStrayModels.CHAIR_RATT_SHOULDER = new ChairRattShoulderModel();
        ModStrayModels.MANDOM = new MandomModel();
        ModStrayModels.MANDOM_WATCH = new WatchModel();
        ModStrayModels.MANDOM_WATCH_SMALL = new SmallWatchModel();
        ModStrayModels.ChestPart = new ChestPart();
        ModStrayModels.SmallChestPart = new SmallChestPart();
        ModStrayModels.PonytailPart = new PonytailPart();
        ModStrayModels.BigHairPart = new BigHairPart();
        ModStrayModels.DiegoHatPart = new DiegoHatPart();
        ModStrayModels.BasicHatPart = new BasicHatPart();
        ModStrayModels.SpikeyHairPart = new SpikeyHairPart();
        ModStrayModels.AvdolHairPart = new AvdolHairPart();
        ModStrayModels.JosukeDecalsPart = new JosukeDecalsPart();
        ModStrayModels.TasselHatPart = new TasselHatPart();
        ModStrayModels.LegCloakPart = new LegCloakPart();
        ModStrayModels.PlayerChestPart = new PlayerChestPart();
        ModStrayModels.PlayerSmallChestPart = new PlayerSmallChestPart();
        ModStrayModels.RightArm = new RightArmPart();
        ModStrayModels.RightArmSlim = new RightArmSlimPart();
        ModStrayModels.LeftArm = new LeftArmPart();
        ModStrayModels.LeftArmSlim = new LeftArmSlimPart();
        ModStrayModels.RightLeg = new RightLegPart();
        ModStrayModels.LeftLeg = new LeftLegPart();
        ModStrayModels.LeftHeel = new LeftHeelPart();
        ModStrayModels.RightHeel = new RightHeelPart();
        ModStrayModels.ROAD_ROLLER = new RoadRollerStrayModel();
        //BlockEntityRenderers.register(ModBlocks.STAND_FIRE_BLOCK_ENTITY, StandFireRenderer::new);
    }
    @SubscribeEvent
    public static void registerParticleStuff(RegisterParticleProvidersEvent event) {
        event.registerSpriteSet(ForgeParticles.HIT_IMPACT.get(), ExplodeParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.PUNCH_IMPACT_A.get(), PunchImpactParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.PUNCH_IMPACT_B.get(), PunchImpactParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.PUNCH_IMPACT_C.get(), PunchImpactParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.PUNCH_MISS.get(), PunchMissParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.MELTING.get(), BloodParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.BLOOD.get(), BloodParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.BLUE_BLOOD.get(), BloodParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.ENDER_BLOOD.get(), BloodParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.POINTER.get(), PointerParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.POINTER_SOFT.get(), SmallPointerParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.AIR_CRACKLE.get(), AirCrackleParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.MENACING.get(), MenacingParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.VACUUM.get(), VacuumParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.ORANGE_FLAME.get(), StandFlameParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.BLUE_FLAME.get(), StandFlameParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.PURPLE_FLAME.get(), StandFlameParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.GREEN_FLAME.get(), StandFlameParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.DREAD_FLAME.get(), StandFlameParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.CREAM_FLAME.get(), StandFlameParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.FOG_CHAIN.get(), FogChainParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.STAR.get(), StarParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.HEART_ATTACK_MINI.get(), HeartAttackMini.Provider::new);
        event.registerSpriteSet(ForgeParticles.ENERGY_DISTORTION.get(), EnergyDistortionParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.PURPLE_STAR.get(), StarParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.BLUE_SPARKLE.get(), BlueSparkleParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.BUBBLE_TRAIL.get(), BubbleTrailParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.WARDEN_CLOCK.get(), WardenClockParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.CLOCK.get(), MandomClockParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.RED_CLOCK.get(), MandomClockParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.BLUE_CLOCK.get(), MandomClockParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.GREEN_CLOCK.get(), MandomClockParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.ORANGE_CLOCK.get(), MandomClockParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.TIME_EMBER.get(), MandomClockParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.ZAP.get(), ZapParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.CINDERELLA_GLOW.get(), CinderellaGlowParticle.CinderellaGlowProvider::new);
        event.registerSpriteSet(ForgeParticles.PINK_SMOKE.get(), CinderellaSmokeParticle.CosyProvider::new);
        event.registerSpriteSet(ForgeParticles.BUBBLE_POP.get(), SoftBubblePopParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.PLUNDER.get(), PlunderParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.FRICTIONLESS.get(), FrictionlessParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.EXCLAMATION.get(), ExclamationParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.D4C_LINES.get(), D4CLinesParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.STITCH.get(), StitchParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.BABY_CRACKLE.get(), BabyCrackleParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.MAGIC_DUST.get(), MagicDustParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.BRIEF_MAGIC_DUST.get(), BriefMagicDustParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.DUST_CRUMBLE.get(), DustCrumbleParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.FIRE_CRUMBLE.get(), FireCrumbleParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.SOUL_FIRE_CRUMBLE.get(), FireCrumbleParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.ROAD_ROLLER_SCRAP.get(), RoadRollerScrapParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.ROAD_ROLLER_EXPLOSION.get(), RoadRollerExplosionParticle.Provider::new);
        event.registerSpriteSet(ForgeParticles.ROAD_ROLLER_SMOKE.get(), RoadRollerSmokeParticle.Provider::new);
    }
}
