package net.hydra.jojomod.particles;

import net.fabricmc.fabric.api.particle.v1.FabricParticleTypes;
import net.hydra.jojomod.Roundabout;
import net.hydra.jojomod.event.ModParticles;
import net.minecraft.core.Registry;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;

public class FabricParticles {
    public static final SimpleParticleType HIT_IMPACT = FabricParticleTypes.simple();
    public static final SimpleParticleType PUNCH_IMPACT_A = FabricParticleTypes.simple();
    public static final SimpleParticleType PUNCH_IMPACT_B = FabricParticleTypes.simple();
    public static final SimpleParticleType PUNCH_IMPACT_C = FabricParticleTypes.simple();
    public static final SimpleParticleType MELTING = FabricParticleTypes.simple();
    public static final SimpleParticleType BLOOD = FabricParticleTypes.simple();
    public static final SimpleParticleType POINTER = FabricParticleTypes.simple();
    public static final SimpleParticleType POINTER_SOFT = FabricParticleTypes.simple();
    public static final SimpleParticleType BLUE_BLOOD = FabricParticleTypes.simple();
    public static final SimpleParticleType ENDER_BLOOD = FabricParticleTypes.simple();
    public static final SimpleParticleType AIR_CRACKLE = FabricParticleTypes.simple();
    public static final SimpleParticleType STAR = FabricParticleTypes.simple();
    public static final SimpleParticleType HEART_ATTACK_MINI = FabricParticleTypes.simple();
    public static final SimpleParticleType ENERGY_DISTORTION = FabricParticleTypes.simple();
    public static final SimpleParticleType PURPLE_STAR = FabricParticleTypes.simple();
    public static final SimpleParticleType MENACING = FabricParticleTypes.simple();
    public static final SimpleParticleType VACUUM = FabricParticleTypes.simple();
    public static final SimpleParticleType ZAP = FabricParticleTypes.simple();
    public static final SimpleParticleType ORANGE_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType BLUE_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType PURPLE_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType GREEN_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType DREAD_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType CREAM_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType FOG_CHAIN = FabricParticleTypes.simple();
    public static final SimpleParticleType BUBBLE_TRAIL = FabricParticleTypes.simple();
    public static final SimpleParticleType WARDEN_CLOCK = FabricParticleTypes.simple();
    public static final SimpleParticleType RED_CLOCK = FabricParticleTypes.simple();
    public static final SimpleParticleType BLUE_CLOCK = FabricParticleTypes.simple();
    public static final SimpleParticleType GREEN_CLOCK = FabricParticleTypes.simple();
    public static final SimpleParticleType ORANGE_CLOCK = FabricParticleTypes.simple();
    public static final SimpleParticleType TIME_EMBER = FabricParticleTypes.simple();
    public static final SimpleParticleType CLOCK = FabricParticleTypes.simple();
    public static final SimpleParticleType CINDERELLA_GLOW = FabricParticleTypes.simple();
    public static final SimpleParticleType PINK_SMOKE = FabricParticleTypes.simple();
    public static final SimpleParticleType D4C_LINES = FabricParticleTypes.simple();
    public static final SimpleParticleType BUBBLE_POP = FabricParticleTypes.simple();
    public static final SimpleParticleType PLUNDER = FabricParticleTypes.simple();
    public static final SimpleParticleType FRICTIONLESS = FabricParticleTypes.simple();
    public static final SimpleParticleType EXCLAMATION = FabricParticleTypes.simple();
    public static final SimpleParticleType BABY_CRACKLE = FabricParticleTypes.simple();
    public static final SimpleParticleType MAGIC_DUST = FabricParticleTypes.simple();
    public static final SimpleParticleType BRIEF_MAGIC_DUST = FabricParticleTypes.simple();
    public static final SimpleParticleType STITCH = FabricParticleTypes.simple();
    public static final SimpleParticleType MOLD_DUST = FabricParticleTypes.simple();
    public static final SimpleParticleType MOLD = FabricParticleTypes.simple();
    public static void registerParticles(){
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("hit_impact"), HIT_IMPACT);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("punch_impact_a"), PUNCH_IMPACT_A);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("punch_impact_b"), PUNCH_IMPACT_B);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("punch_impact_c"), PUNCH_IMPACT_C);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("melting"), MELTING);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("blood"), BLOOD);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("pointer"), POINTER);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("pointer_soft"), POINTER_SOFT);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("star"), STAR);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("heart_attack_mini"), HEART_ATTACK_MINI);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("energy_distortion"), ENERGY_DISTORTION);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("purple_star"), PURPLE_STAR);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("blue_blood"), BLUE_BLOOD);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("ender_blood"), ENDER_BLOOD);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("air_crackle"), AIR_CRACKLE);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("menacing"), MENACING);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("vacuum"), VACUUM);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("zap"), ZAP);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("fog_chain"), FOG_CHAIN);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("bubble_trail"), BUBBLE_TRAIL);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("warden_clock"), WARDEN_CLOCK);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("orange_flame"), ORANGE_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("blue_flame"), BLUE_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("purple_flame"), PURPLE_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("green_flame"), GREEN_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("dread_flame"), DREAD_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("cream_flame"), CREAM_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("cinderella_glow"), CINDERELLA_GLOW);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("pink_smoke"), PINK_SMOKE);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("soft_bubble_pop"), BUBBLE_POP);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("plunder"), PLUNDER);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("frictionless"), FRICTIONLESS);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("exclamation"), EXCLAMATION);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("d4c_lines"), D4C_LINES);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("stitch"), STITCH);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("mold_dust"), MOLD_DUST);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("mold"), MOLD);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("clock"), CLOCK);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("red_clock"), RED_CLOCK);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("blue_clock"), BLUE_CLOCK);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("green_clock"), GREEN_CLOCK);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("orange_clock"), ORANGE_CLOCK);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("time_ember"), TIME_EMBER);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("baby_crackle"), BABY_CRACKLE);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("magic_dust"), MAGIC_DUST);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("brief_magic_dust"), BRIEF_MAGIC_DUST);

        ModParticles.MELTING = MELTING;
        ModParticles.BLOOD = BLOOD;
        ModParticles.BLUE_BLOOD = BLUE_BLOOD;
        ModParticles.ENDER_BLOOD = ENDER_BLOOD;
        ModParticles.HIT_IMPACT = HIT_IMPACT;
        ModParticles.AIR_CRACKLE = AIR_CRACKLE;
        ModParticles.MENACING = MENACING;
        ModParticles.PUNCH_IMPACT_A = PUNCH_IMPACT_A;
        ModParticles.PUNCH_IMPACT_B = PUNCH_IMPACT_B;
        ModParticles.PUNCH_IMPACT_C = PUNCH_IMPACT_C;
        ModParticles.VACUUM = VACUUM;
        ModParticles.STAR = STAR;
        ModParticles.HEART_ATTACK_MINI = HEART_ATTACK_MINI;
        ModParticles.ENERGY_DISTORTION = ENERGY_DISTORTION;
        ModParticles.PURPLE_STAR = PURPLE_STAR;
        ModParticles.FOG_CHAIN = FOG_CHAIN;
        ModParticles.BUBBLE_TRAIL = BUBBLE_TRAIL;
        ModParticles.WARDEN_CLOCK = WARDEN_CLOCK;
        ModParticles.CLOCK = CLOCK;
        ModParticles.RED_CLOCK = RED_CLOCK;
        ModParticles.BLUE_CLOCK = BLUE_CLOCK;
        ModParticles.GREEN_CLOCK = GREEN_CLOCK;
        ModParticles.ORANGE_CLOCK = ORANGE_CLOCK;
        ModParticles.TIME_EMBER = TIME_EMBER;
        ModParticles.POINTER = POINTER;
        ModParticles.ZAP = ZAP;
        ModParticles.POINTER_SOFT = POINTER_SOFT;
        ModParticles.ORANGE_FLAME = ORANGE_FLAME;
        ModParticles.BLUE_FLAME = BLUE_FLAME;
        ModParticles.PURPLE_FLAME = PURPLE_FLAME;
        ModParticles.GREEN_FLAME = GREEN_FLAME;
        ModParticles.DREAD_FLAME = DREAD_FLAME;
        ModParticles.CREAM_FLAME = CREAM_FLAME;
        ModParticles.CINDERELLA_GLOW = CINDERELLA_GLOW;
        ModParticles.D4C_LINES = D4C_LINES;
        ModParticles.PINK_SMOKE = PINK_SMOKE;
        ModParticles.BUBBLE_POP = BUBBLE_POP;
        ModParticles.PLUNDER = PLUNDER;
        ModParticles.FRICTIONLESS = FRICTIONLESS;
        ModParticles.EXCLAMATION = EXCLAMATION;
        ModParticles.BABY_CRACKLE = BABY_CRACKLE;
        ModParticles.MAGIC_DUST = MAGIC_DUST;
        ModParticles.BRIEF_MAGIC_DUST = BRIEF_MAGIC_DUST;
        ModParticles.STITCH = STITCH;
        ModParticles.MOLD_DUST = MOLD_DUST;
        ModParticles.MOLD = MOLD;
    }
}
