package net.hydra.jojomod.particles;

import net.fabricmc.fabric.api.particle.v1.FabricParticleTypes;
import net.hydra.jojomod.Roundabout;
import net.hydra.jojomod.event.ModParticles;
import net.minecraft.core.Registry;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;

public class FabricParticles {
    public static final SimpleParticleType HIT_IMPACT = FabricParticleTypes.simple();
    public static final SimpleParticleType BLOOD = FabricParticleTypes.simple();
    public static final SimpleParticleType POINTER = FabricParticleTypes.simple();
    public static final SimpleParticleType POINTER_SOFT = FabricParticleTypes.simple();
    public static final SimpleParticleType BLUE_BLOOD = FabricParticleTypes.simple();
    public static final SimpleParticleType ENDER_BLOOD = FabricParticleTypes.simple();
    public static final SimpleParticleType AIR_CRACKLE = FabricParticleTypes.simple();
    public static final SimpleParticleType STAR = FabricParticleTypes.simple();
    public static final SimpleParticleType HEART_ATTACK_MINI = FabricParticleTypes.simple();
    public static final SimpleParticleType ENERGY_DISTORTION = FabricParticleTypes.simple();
    public static final SimpleParticleType PURPLE_STAR = FabricParticleTypes.simple();
    public static final SimpleParticleType MENACING = FabricParticleTypes.simple();
    public static final SimpleParticleType VACUUM = FabricParticleTypes.simple();
    public static final SimpleParticleType ORANGE_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType BLUE_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType PURPLE_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType GREEN_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType DREAD_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType CREAM_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType FOG_CHAIN = FabricParticleTypes.simple();
    public static final SimpleParticleType BUBBLE_TRAIL = FabricParticleTypes.simple();
    public static final SimpleParticleType WARDEN_CLOCK = FabricParticleTypes.simple();
    public static final SimpleParticleType CINDERELLA_GLOW = FabricParticleTypes.simple();
    public static final SimpleParticleType PINK_SMOKE = FabricParticleTypes.simple();
    public static final SimpleParticleType D4C_LINES = FabricParticleTypes.simple();
    public static final SimpleParticleType BUBBLE_POP = FabricParticleTypes.simple();
    public static final SimpleParticleType PLUNDER = FabricParticleTypes.simple();
    public static final SimpleParticleType FRICTIONLESS = FabricParticleTypes.simple();
    public static final SimpleParticleType EXCLAMATION = FabricParticleTypes.simple();
    public static final SimpleParticleType STITCH = FabricParticleTypes.simple();
    public static void registerParticles(){
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("hit_impact"), HIT_IMPACT);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("blood"), BLOOD);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("pointer"), POINTER);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("pointer_soft"), POINTER_SOFT);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("star"), STAR);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("heart_attack_mini"), HEART_ATTACK_MINI);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("energy_distortion"), ENERGY_DISTORTION);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("purple_star"), PURPLE_STAR);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("blue_blood"), BLUE_BLOOD);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("ender_blood"), ENDER_BLOOD);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("air_crackle"), AIR_CRACKLE);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("menacing"), MENACING);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("vacuum"), VACUUM);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("fog_chain"), FOG_CHAIN);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("bubble_trail"), BUBBLE_TRAIL);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("warden_clock"), WARDEN_CLOCK);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("orange_flame"), ORANGE_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("blue_flame"), BLUE_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("purple_flame"), PURPLE_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("green_flame"), GREEN_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("dread_flame"), DREAD_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("cream_flame"), CREAM_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("cinderella_glow"), CINDERELLA_GLOW);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("pink_smoke"), PINK_SMOKE);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("soft_bubble_pop"), BUBBLE_POP);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("plunder"), PLUNDER);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("frictionless"), FRICTIONLESS);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("exclamation"), EXCLAMATION);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("d4c_lines"), D4C_LINES);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("stitch"), STITCH);

        ModParticles.BLOOD = BLOOD;
        ModParticles.BLUE_BLOOD = BLUE_BLOOD;
        ModParticles.ENDER_BLOOD = ENDER_BLOOD;
        ModParticles.HIT_IMPACT = HIT_IMPACT;
        ModParticles.AIR_CRACKLE = AIR_CRACKLE;
        ModParticles.MENACING = MENACING;
        ModParticles.VACUUM = VACUUM;
        ModParticles.STAR = STAR;
        ModParticles.HEART_ATTACK_MINI = HEART_ATTACK_MINI;
        ModParticles.ENERGY_DISTORTION = ENERGY_DISTORTION;
        ModParticles.PURPLE_STAR = PURPLE_STAR;
        ModParticles.FOG_CHAIN = FOG_CHAIN;
        ModParticles.BUBBLE_TRAIL = BUBBLE_TRAIL;
        ModParticles.WARDEN_CLOCK = WARDEN_CLOCK;
        ModParticles.POINTER = POINTER;
        ModParticles.POINTER_SOFT = POINTER_SOFT;
        ModParticles.ORANGE_FLAME = ORANGE_FLAME;
        ModParticles.BLUE_FLAME = BLUE_FLAME;
        ModParticles.PURPLE_FLAME = PURPLE_FLAME;
        ModParticles.GREEN_FLAME = GREEN_FLAME;
        ModParticles.DREAD_FLAME = DREAD_FLAME;
        ModParticles.CREAM_FLAME = CREAM_FLAME;
        ModParticles.CINDERELLA_GLOW = CINDERELLA_GLOW;
        ModParticles.D4C_LINES = D4C_LINES;
        ModParticles.PINK_SMOKE = PINK_SMOKE;
        ModParticles.BUBBLE_POP = BUBBLE_POP;
        ModParticles.PLUNDER = PLUNDER;
        ModParticles.FRICTIONLESS = FRICTIONLESS;
        ModParticles.EXCLAMATION = EXCLAMATION;
        ModParticles.STITCH = STITCH;
    }
}
