package net.hydra.jojomod.particles;

import net.fabricmc.fabric.api.particle.v1.FabricParticleTypes;
import net.hydra.jojomod.Roundabout;
import net.hydra.jojomod.event.ModParticles;
import net.minecraft.core.Registry;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;

public class FabricParticles {
    public static final SimpleParticleType HIT_IMPACT = FabricParticleTypes.simple();
    public static final SimpleParticleType BLOOD = FabricParticleTypes.simple();
    public static final SimpleParticleType POINTER = FabricParticleTypes.simple();
    public static final SimpleParticleType BLUE_BLOOD = FabricParticleTypes.simple();
    public static final SimpleParticleType ENDER_BLOOD = FabricParticleTypes.simple();
    public static final SimpleParticleType AIR_CRACKLE = FabricParticleTypes.simple();
    public static final SimpleParticleType MENACING = FabricParticleTypes.simple();
    public static final SimpleParticleType VACUUM = FabricParticleTypes.simple();
    public static final SimpleParticleType ORANGE_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType BLUE_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType PURPLE_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType GREEN_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType DREAD_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType CREAM_FLAME = FabricParticleTypes.simple();
    public static final SimpleParticleType FOG_CHAIN = FabricParticleTypes.simple();
    public static final SimpleParticleType WARDEN_CLOCK = FabricParticleTypes.simple();
    public static final SimpleParticleType CINDERELLA_GLOW = FabricParticleTypes.simple();
    public static final SimpleParticleType PINK_SMOKE = FabricParticleTypes.simple();
    public static final SimpleParticleType D4C_LINES = FabricParticleTypes.simple();
    public static final SimpleParticleType BUBBLE_POP = FabricParticleTypes.simple();
    public static final SimpleParticleType PLUNDER = FabricParticleTypes.simple();
    public static final SimpleParticleType FRICTIONLESS = FabricParticleTypes.simple();
    public static void registerParticles(){
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "hit_impact"), HIT_IMPACT);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "blood"), BLOOD);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "pointer"), POINTER);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "blue_blood"), BLUE_BLOOD);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "ender_blood"), ENDER_BLOOD);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "air_crackle"), AIR_CRACKLE);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "menacing"), MENACING);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "vacuum"), VACUUM);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "fog_chain"), FOG_CHAIN);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "warden_clock"), WARDEN_CLOCK);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "orange_flame"), ORANGE_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "blue_flame"), BLUE_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "purple_flame"), PURPLE_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "green_flame"), GREEN_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "dread_flame"), DREAD_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "cream_flame"), CREAM_FLAME);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "cinderella_glow"), CINDERELLA_GLOW);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "pink_smoke"), PINK_SMOKE);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "soft_bubble_pop"), BUBBLE_POP);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "plunder"), PLUNDER);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, new ResourceLocation(Roundabout.MOD_ID, "frictionless"), FRICTIONLESS);
        Registry.register(BuiltInRegistries.PARTICLE_TYPE, Roundabout.location("d4c_lines"), D4C_LINES);

        ModParticles.BLOOD = BLOOD;
        ModParticles.BLUE_BLOOD = BLUE_BLOOD;
        ModParticles.ENDER_BLOOD = ENDER_BLOOD;
        ModParticles.HIT_IMPACT = HIT_IMPACT;
        ModParticles.AIR_CRACKLE = AIR_CRACKLE;
        ModParticles.MENACING = MENACING;
        ModParticles.VACUUM = VACUUM;
        ModParticles.FOG_CHAIN = FOG_CHAIN;
        ModParticles.WARDEN_CLOCK = WARDEN_CLOCK;
        ModParticles.POINTER = POINTER;
        ModParticles.ORANGE_FLAME = ORANGE_FLAME;
        ModParticles.BLUE_FLAME = BLUE_FLAME;
        ModParticles.PURPLE_FLAME = PURPLE_FLAME;
        ModParticles.GREEN_FLAME = GREEN_FLAME;
        ModParticles.DREAD_FLAME = DREAD_FLAME;
        ModParticles.CREAM_FLAME = CREAM_FLAME;
        ModParticles.CINDERELLA_GLOW = CINDERELLA_GLOW;
        ModParticles.D4C_LINES = D4C_LINES;
        ModParticles.PINK_SMOKE = PINK_SMOKE;
        ModParticles.BUBBLE_POP = BUBBLE_POP;
        ModParticles.PLUNDER = PLUNDER;
        ModParticles.FRICTIONLESS = FRICTIONLESS;
    }
}
