package net.hydra.jojomod.access;

import net.hydra.jojomod.util.PlayerMaskSlots;
import net.minecraft.world.entity.AnimationState;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.item.ItemStack;

public interface IPlayerEntity {
    Inventory roundabout$GetInventory();

    void roundabout$SetPos(byte Pos);
    int roundabout$getAirTime();
    int roundabout$getClientDodgeTime();
    int roundabout$getControlling();
    void roundabout$setIsControlling(int pilot);
    int roundabout$getDodgeTime();
    void roundabout$addStandExp(int amt);
    int roundabout$getCameraHits();
    void roundabout$setCameraHits(int ticks);
    void roundabout$setClientDodgeTime(int dodgeTime);
    void roundabout$setDodgeTime(int dodgeTime);
    void roundabout$setAirTime(int airTime);
    void roundabout$setShapeShift(byte level);
    void roundabout$shapeShiftSilent();
    void roundabout$shapeShift();
    void roundabout$setShapeShiftExtraData(byte level);
    byte roundabout$getShapeShift();
    byte roundabout$getShapeShiftExtraData();
    byte roundabout$GetPos();
    void roundabout$SetPoseEmote(byte Pos);
    byte roundabout$GetPoseEmote();
    void roundabout$addKnife();
    void roundabout$setKnife(byte knives);
    int roundabout$getKnifeCount();
    ItemStack roundabout$getMaskSlot();
    ItemStack roundabout$getMaskVoiceSlot();
    void roundabout$setMaskSlot(ItemStack stack);
    void roundabout$setMaskVoiceSlot(ItemStack stack);
    PlayerMaskSlots roundabout$getMaskInventory();
    void roundabout$setMaskInventory(PlayerMaskSlots pm);
    void roundabout$setStandLevel(byte level);
    byte roundabout$getStandLevel();
    void roundabout$showExp(boolean keyIsDown);
    boolean roundabout$getDisplayExp();
    void roundabout$setStandExp(int level);
    int roundabout$getStandExp();
    boolean roundabout$getUnlockedBonusSkin();
    byte roundabout$getStandSkin();
    void roundabout$setStandSkin(byte level);
    void roundabout$setIdlePos(byte level);
    byte roundabout$getIdlePos();
    void roundabout$setUnlockedBonusSkin(boolean unlock);
    int roundabout$getAnchorPlace();
    void roundabout$setAnchorPlace(int anchorPlace);
    float roundabout$getDistanceOut();
    void roundabout$setDistanceOut(float distanceOut);
    float roundabout$getSizePercent();
    void roundabout$setSizePercent(float idleOpacity);
    float roundabout$getIdleRotation();
    void roundabout$setIdleRotation(float combatOpacity);
    float roundabout$getIdleYOffset();
    void roundabout$setIdleYOffset(float enemyOpacity);
    AnimationState getWry();
    AnimationState getGiorno();
    AnimationState getKoichi();
    AnimationState getOhNo();
    AnimationState getJoseph();
    AnimationState getTortureDance();
    AnimationState getWamuu();
    AnimationState getJonathan();
    AnimationState getJotaro();

}
